export const API_DEFAULT_PARAMS = {
  PER_PAGE: 100,
  PAGE: 1
}

export const DEBOUNCE_TIME = 500

export const MINIMUN_SEARCH_KEY = 3

export const IMAGE_PLACEHOLDER =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkqAcAAIUAgUW0RjgAAAAASUVORK5CYII='
